server:
  port: 8081
spring:
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.14.59:3306/test?autoreconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: lonch
      password: lonch@123
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat, wall, log4j
    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.14.59:3306/clinicpad?autoreconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: lonch
      password: lonch@123
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat, wall, log4j
